[project]
name = "upphandlat-mcp"
version = "0.1.0"
description = "MCP server for CSV aggregation and analysis using Polars"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",  # MCP SDK with CLI for development
    "polars>=0.19.0",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
    "python-dotenv>=1.0.0",
]
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "Apache-2.0" } # Or your preferred license

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
"Homepage" = "https://github.com/yourusername/upphandlat-mcp" # Example URL
"Bug Tracker" = "https://github.com/yourusername/upphandlat-mcp/issues" # Example URL

[project.scripts]
upphandlat-mcp = "upphandlat_mcp:main"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "PL", "PYI"] # Common useful rules

[tool.pyright]
# Pyright configurations (optional, but good for type checking)
include = ["src/upphandlat_mcp"]
pythonVersion = "3.13"
reportMissingImports = "warning"
reportTypedDictNotRequiredAccess = "none"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"